site_name: ImGraph
site_description: "This is a project to convert image to graph and apply learning methods on graphs."

repo_url: https://github.com/aryan-at-ul/imgraph
repo_name: imgraph

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "green"
      accent: "white"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "imgraph": index.md
  - "imgraph.pipeline": pipeline.md
  - "imgraph.data": data.md
  - "imgraph.reader": reader.md
  - "imgraph.writer": writer.md
  - "imgraph.datasets" : datasets.md
